import AppKit

/// Watches the system pasteboard and reports new clipboard content.
/// Polls `changeCount` (like RustCast's 100 ms arboard loop) and classifies
/// content as image, URL or text.
///
/// Borrowed from Maccy's Clipboard.swift:
/// - Copies made by HeyCast itself are tagged with `selfMarkerType` and
///   ignored, so re-copying a history entry (or copying a calculator result)
///   doesn't pollute or reorder the history.
/// - Pasteboards marked concealed/transient/auto-generated (password
///   managers, one-time codes) are never recorded.
final class ClipboardService {
    enum Content: Equatable {
        case text(String)
        case url(String)
        case image(Data)
    }

    struct Capture: Equatable {
        var content: Content
        var source: Source?
    }

    /// The app that was frontmost when the copy happened.
    struct Source: Equatable {
        var bundleID: String
        var name: String
    }

    static let selfMarkerType = NSPasteboard.PasteboardType("org.heycast.self")

    /// nspasteboard.org conventions plus Apple's private equivalents; data
    /// marked with any of these is secret or ephemeral and must not be kept.
    private static let ignoredTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.apple.is.concealed"),
        NSPasteboard.PasteboardType("com.apple.is.transient"),
    ]

    var onCapture: ((Capture) -> Void)?

    private var timer: Timer?
    private var lastChangeCount: Int
    private var lastContent: Content?

    init() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func start(interval: TimeInterval = 0.1) {
        guard timer == nil else { return }
        timer = Timer.scheduledTimer(withTimeInterval: interval, repeats: true) { [weak self] _ in
            self?.poll()
        }
        RunLoop.main.add(timer!, forMode: .common)
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount

        let types = Set(pb.types ?? [])
        // HeyCast's own writes and secret/transient data: never record them.
        // Clear lastContent so the next external copy isn't mistaken for a
        // repeat of whatever was captured before the ignored event.
        if types.contains(Self.selfMarkerType) || !types.isDisjoint(with: Self.ignoredTypes) {
            lastContent = nil
            return
        }

        let content = classify(pasteboard: pb)
        guard let content, content != lastContent else { return }
        lastContent = content
        let source = NSWorkspace.shared.frontmostApplication.flatMap { app -> Source? in
            guard let bundleID = app.bundleIdentifier else { return nil }
            return Source(bundleID: bundleID, name: app.localizedName ?? bundleID)
        }
        onCapture?(Capture(content: content, source: source))
    }

    private func classify(pasteboard: NSPasteboard) -> Content? {
        // Images first (screenshots etc.)
        if let png = pasteboard.data(forType: .png) {
            return .image(png)
        }
        if let tiff = pasteboard.data(forType: .tiff),
           let image = NSImage(data: tiff),
           let tiff2 = image.tiffRepresentation,
           let rep = NSBitmapImageRep(data: tiff2),
           let png = rep.representation(using: .png, properties: [:]) {
            return .image(png)
        }
        guard let text = pasteboard.string(forType: .string)?
            .trimmingCharacters(in: .whitespacesAndNewlines), !text.isEmpty else { return nil }
        if let url = URL(string: text), url.host != nil || (url.scheme != nil && text.contains(".")) {
            return .url(text)
        }
        return .text(text)
    }

    private static func tagSelf(_ pb: NSPasteboard) {
        pb.setString("", forType: Self.selfMarkerType)
    }

    /// Write an entry back to the system clipboard.
    static func copy(entry: ClipboardEntry) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch entry.kind {
        case .image:
            if let data = entry.imageData {
                pb.setData(data, forType: .png)
            }
        case .url, .text:
            pb.setString(entry.text ?? "", forType: .string)
        }
        tagSelf(pb)
    }

    static func copy(text: String) {
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(text, forType: .string)
        tagSelf(pb)
    }

    /// Posts a synthetic Cmd+V to the previously-frontmost app so selecting a
    /// clipboard entry pastes it in place (paste-on-select).
    static func simulatePaste(toPid pid: pid_t) {
        guard let keyDown = CGEvent(keyboardEventSource: nil, virtualKey: 9 /* V */, keyDown: true),
              let keyUp = CGEvent(keyboardEventSource: nil, virtualKey: 9, keyDown: false) else { return }
        keyDown.flags = .maskCommand
        keyUp.flags = .maskCommand
        keyDown.postToPid(pid)
        keyUp.postToPid(pid)
    }

    private static let pasteboard = NSPasteboard.general

    /// True when the system clipboard currently holds an image.
    static var clipboardHasImage: Bool {
        pasteboard.types?.contains { $0 == .png || $0 == .tiff } ?? false
    }

    /// The clipboard image as PNG (screenshots land as TIFF or PNG), long
    /// edge downscaled to 2000px so requests stay a sane size.
    static func clipboardImagePNG() -> Data? {
        var data = pasteboard.data(forType: .png)
        if data == nil, let tiff = pasteboard.data(forType: .tiff) {
            data = tiff
        }
        guard var data, let image = NSImage(data: data) else { return nil }

        let longest = max(image.size.width, image.size.height)
        if longest > 2000 {
            let scale = 2000 / longest
            let newSize = NSSize(width: (image.size.width * scale).rounded(),
                                 height: (image.size.height * scale).rounded())
            guard let rep = NSBitmapImageRep(
                bitmapDataPlanes: nil,
                pixelsWide: Int(newSize.width), pixelsHigh: Int(newSize.height),
                bitsPerSample: 8, samplesPerPixel: 4,
                hasAlpha: true, isPlanar: false,
                colorSpaceName: .calibratedRGB, bytesPerRow: 0, bitsPerPixel: 0) else { return data }
            rep.size = newSize
            NSGraphicsContext.saveGraphicsState()
            NSGraphicsContext.current = NSGraphicsContext(bitmapImageRep: rep)
            image.draw(in: NSRect(origin: .zero, size: newSize),
                       from: .zero, operation: .copy, fraction: 1.0)
            NSGraphicsContext.restoreGraphicsState()
            data = rep.representation(using: .png, properties: [:]) ?? data
        }
        return data
    }
}
